services:
  - type: web
    name: youtube-music-api
    runtime: python
    region: oregon
    buildCommand: |
      echo "🔧 Updating apt-get and installing ffmpeg..."
      apt-get update && apt-get install -y ffmpeg
      echo "✅ ffmpeg installed!"

      echo "📦 Installing Python dependencies..."
      pip install -r requirements.txt
      echo "✅ Dependencies installed!"
    startCommand: gunicorn src.app:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: FFMPEG_PATH
        value: ffmpeg
    plan: free
